name: Check Code Quality

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5

      - name: Set up Node.js
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6
        with:
          node-version-file: ".node-version"

      - name: Set up pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4
        with:
          version: 11.8.0

      - name: Install dependencies
        run: pnpm install

      - name: Run lint with Biome
        run: pnpm run check

      - name: Run tests with Vitest
        run: pnpm run test

      - name: TypeScript type check
        run: pnpm exec tsc --noEmit

      - name: Run build test
        run: pnpm run build
